version: "3.8"

services:
  server:
    build: ./server
    container_name: movie_server
    env_file: 
      - .env
    environment:
      # Optionally, you can override or ensure the env is set
      - TMDB_API_KEY=${TMDB_API_KEY}
    ports:
      - "3001:3001"
    # If you'd like to restart automatically
    # restart: unless-stopped

  client:
    build: ./client
    container_name: movie_client
    ports:
      #- "3000:80"     # If using Nginx approach (port 80 in the container)
      - 3000:3000 # or if using the Node 'serve' approach
    depends_on:
      - server
    # restart: unless-stopped
